### PR TITLE
Use quorum reads for locks

### PR DESCRIPTION
**Pull request by thepwagner**
Background at: https://coreos.com/etcd/docs/0.4.7/etcd-api/#read-consistency

The transient "Lock not found" errors are caused by the client not being able
to read it's own write. By requiring a quorum on read, we ensure
consistency.

### CODE REVIEW

**Comment by thepwagner** [comment]
@lrvick

**Comment by thepwagner** [comment]
@aheckmann @lrvick @AvianFlu @DeviaVir ; sorry I'd forgotten about this (thanks, JIRA+Github plugin!)

**Comment by aheckmann** [comment]
:+1:

**Comment by DeviaVir** [comment]
:+1:

**Pull request merged**
